version: '2'
services:
 app:
  image: nginx
  container_name: ws3-aplb.branconet.com
  volumes:
   - /media/pi/pi-ssd/share_files/Websites/aplb.branconet.com:/usr/share/nginx/html
  ports:
   - "8083:80"
  environment:
   - NGINX_HOST=aplb.branconet.com
   - NGINX_PORT=80