version: '2'
services:
 app:
  image: nginx
  container_name: proxyserver
  volumes:
   - /media/pi/pi-ssd/share_files/Websites/reverseproxy/sites:/usr/share/nginx/html
   - /media/pi/pi-ssd/container-program-files/Websites/reverseproxy/config:/etc/nginx/conf.d
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=proxy.branconet.com
   - NGINX_PORT=80