version: "3.7"

services:

  php:
    image: php:7.2-fpm
    volumes:
      - /media/pi/pi-ssd/share_files/Websites/phpserver/sites:/var/www/myapp
      - /media/pi/pi-ssd/container-program-files/Websites/phpserver/php.ini:/usr/local/etc/php/php.ini